### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by piotryordanov** [acannibalox/neomutt#1]
How exactly am I supposed to install this? :)

**Comment by acannibalox** [comment]
You just need to install neomutt and then pull this down...so something like:
pacman -S neomutt
git clone git@github.com:acannibalox/neomutt.git ~/.mutt
ln -s ~/.mutt/.muttrc ~/.muttrc
cd ~/.mutt && mkdir cache certificates headers messages secrets temp
